### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by bmumford** [bmumford/SEBC#1]

**Comment by mfernest** [comment]
Please leave Issues open until they are evaluated. Once you close them they fall off my radar.

**Comment by mfernest** [comment]
It's worth mentioning that git and GitHub are primarily intended to store text files. You can store binary types as well, but git does not know how to slice these files into blocks for more efficient storage. 

I've accepted text output in favor of screenshots for many submissions so the repos don't just get bigger and bigger.

Not a problem with your work here, just a note for future reference.

**Comment by mfernest** [comment]
It is indeed a little difficult to trace through all your work for this lab. The effort and persistence are commendable.

Completed.
